apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: activemq
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: activemq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: activemq
    spec:
      containers:
      - env:
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: admin
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: admin
        image: webcenter/activemq:latest
        imagePullPolicy: ""
        name: activemq
        ports:
        - containerPort: 61613
        - containerPort: 61616
        - containerPort: 8161
        resources: {}
        volumeMounts:
        - mountPath: /data/activemq
          name: activemq-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: activemq-data
        persistentVolumeClaim:
          claimName: activemq-data
status: {}
