apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          valueFrom:
            configMapKeyRef:
              key: GF_INSTALL_PLUGINS
              name: grafana-config-monitoring
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GF_SECURITY_ADMIN_PASSWORD
              name: grafana-config-monitoring
        - name: GF_USERS_ALLOW_SIGN_UP
          valueFrom:
            configMapKeyRef:
              key: GF_USERS_ALLOW_SIGN_UP
              name: grafana-config-monitoring
        image: grafana/grafana:latest
        imagePullPolicy: ""
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
        securityContext:
          runAsUser: 104
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        - mountPath: /etc/grafana/provisioning
          name: grafana-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
      - name: grafana-claim1
        persistentVolumeClaim:
          claimName: grafana-claim1
status: {}
