apiVersion: v1
data:
  GF_INSTALL_PLUGINS: grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5,https://download.sysdig.com/stable/grafana-sysdig-datasource/grafana-sysdig-datasource-v0.7.zip;sysdig
  GF_SECURITY_ADMIN_PASSWORD: admin
  GF_USERS_ALLOW_SIGN_UP: "false"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-grafana-config-monitoring
  name: grafana-config-monitoring
