apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: infinispan
  name: infinispan
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: infinispan
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: infinispan
    spec:
      containers:
      - env:
        - name: PASS
          value: user
        - name: USER
          value: user
        image: infinispan/server:10.1.5.Final
        imagePullPolicy: ""
        name: infinispan
        ports:
        - containerPort: 11222
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
