# Fake certificates for skaffold, same as in oc-web/config/nginx/ssl
apiVersion: v1
stringData:
  ssh-privatekey: |-
    -----BEGIN CERTIFICATE-----
    MIIDPDCCAiQCCQCEb6K1kZbFLTANBgkqhkiG9w0BAQsFADBgMQswCQYDVQQGEwJJ
    RTEPMA0GA1UECgwGVXRtb3N0MRQwEgYDVQQLDAtFbmdpbmVlcmluZzEqMCgGCSqG
    SIb3DQEJARYbcnlzemFyZC5wZXJrb3dza2lAdXRtb3N0LmNvMB4XDTIxMDMyMjEw
    MTIyNVoXDTI5MDgxMjEwMTIyNVowYDELMAkGA1UEBhMCSUUxDzANBgNVBAoMBlV0
    bW9zdDEUMBIGA1UECwwLRW5naW5lZXJpbmcxKjAoBgkqhkiG9w0BCQEWG3J5c3ph
    cmQucGVya293c2tpQHV0bW9zdC5jbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBAL6Z3wo+ChwuKEsBp05GMDH4R+IknvZ0VfF7Yz7p5TydaNQV3DC5bZBj
    feHUiIY0FExnv4rWIhAb39b64Qvbzhf75UmmIps1ie6GpP3p+Uprgq48YkCpP9dq
    MabG8Tb2zVXJAZMQWo6o4r2+Qvror2EVWT7k/IzU7udjU7GkyqcryyN/QfmS0MIl
    lzEIrLvw2CpiOOSM4QvPOfaD70tAJnyQfrGwjTJaOrEB1mYaX405QeexeDLYTd/2
    VkRUkjMRdsfdoZGZmMJic4oDidhGHajYhbt7C/iGWrn7vdweoVd7h1OOwGZL4s8a
    jnO5dAkuHv2sCH1h+JcBYER/inDU/zkCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
    tntGjN74Rn1r8bJURY93cvQODRv5Kqdft92CJxBPcJ35EaWROPcugJKWefSPb2B8
    tlLr4OeuAjzJLwSwSsq24AnSjOP1oJygm4DWUVRHrvPlUT311Upo/PD7W4wz5Rij
    05CS0TtPRwXa7GEd+H2eth+kEkkSxhi3PNHxHGlU4f6D/xd2LCr57slsF54wwC+A
    LpEKxPoFaa6DrjRpbmm+8OJHKZq8VbK3NtDSQ8mwuFZOtWgonCehbzFMFXwpyOaV
    m+6PSU7ZN6yeM6KGVahmns6fC1T5z9zSpBIbmugLp/cQaBRAxeoEX88SW0AaZgmB
    IrZC+HX43FMFfqlBiRpveA==
    -----END CERTIFICATE-----

kind: Secret
metadata:
  name: ssh-auth
  namespace: default
type: Opaque