apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-dbs.sql: |-
    CREATE DATABASE "gwp";
    CREATE DATABASE "gms-oc-db";
    CREATE DATABASE "camunda-db";
    CREATE DATABASE "utmost-oc-db";
    CREATE DATABASE "tae";
    CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch";
    CREATE EXTENSION IF NOT EXISTS "pg_trgm";
    CREATE DATABASE "uci";
