apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-exporter
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-exporter
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_NAME
          value: postgresql://postgres@postgres:5432/?sslmode=disable
        image: wrouesnel/postgres_exporter:v0.8.0
        name: postgres-exporter
        ports:
        - containerPort: 9187
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
